//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::accounts::Entity as Accounts;
pub use super::accounts::Model as AccountsModel;
pub use super::accounts::ActiveModel as AccountsActiveModel;

pub use super::proposals::Entity as Proposals;
pub use super::proposals::Model as ProposalsModel;
pub use super::proposals::ActiveModel as ProposalsActiveModel;