//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "proposals")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub author: String,
    pub block_number: i64,
    #[sea_orm(column_type = "Text")]
    pub ipfs_hash: String,
    #[sea_orm(column_type = "Text")]
    #[serde(skip_deserializing)]
    pub root_hash: String,
    #[serde(skip_deserializing)]
    pub created_at: Option<DateTime>,
    #[sea_orm(ignore)]
    #[serde(skip_deserializing)]
    pub accounts: Vec<super::accounts::Model>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::accounts::Entity")]
    Accounts,
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Accounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
